title: CatPaw
description: Docs and other information related to CatPaw!
remote_theme: just-the-docs/just-the-docs-template

url: https://activexdiamond.github.io/cat-paw/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/ActivexDiamond/cat-paw
